// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SurvivorWebAPI.Data;

#nullable disable

namespace SurvivorWebAPI.Migrations
{
    [DbContext(typeof(SurvivorContext))]
    [Migration("20241228091642_Ikinci")]
    partial class Ikinci
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SurvivorWebAPI.Data.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2024, 12, 28, 9, 16, 41, 510, DateTimeKind.Utc).AddTicks(9942),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(2024, 12, 28, 9, 16, 41, 510, DateTimeKind.Utc).AddTicks(9952),
                            Name = "Unluler"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2024, 12, 28, 9, 16, 41, 510, DateTimeKind.Utc).AddTicks(9966),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(2024, 12, 28, 9, 16, 41, 510, DateTimeKind.Utc).AddTicks(9967),
                            Name = "Gonulluler"
                        });
                });

            modelBuilder.Entity("SurvivorWebAPI.Data.Entity.Competitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Competitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(50),
                            FirstName = "Acun",
                            IsDeleted = false,
                            LastName = "Ilicali",
                            ModifiedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(51)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(57),
                            FirstName = "Aleyna",
                            IsDeleted = false,
                            LastName = "Avci",
                            ModifiedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(58)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(62),
                            FirstName = "Hadise",
                            IsDeleted = false,
                            LastName = "Acikgoz",
                            ModifiedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(63)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(66),
                            FirstName = "Sertan",
                            IsDeleted = false,
                            LastName = "Bozkus",
                            ModifiedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(66)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(69),
                            FirstName = "Ozge",
                            IsDeleted = false,
                            LastName = "Acik",
                            ModifiedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(69)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(79),
                            FirstName = "Kivanc",
                            IsDeleted = false,
                            LastName = "Tatlitug",
                            ModifiedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(80)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(82),
                            FirstName = "Ahmet",
                            IsDeleted = false,
                            LastName = "Yilmaz",
                            ModifiedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(83)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(85),
                            FirstName = "Elif",
                            IsDeleted = false,
                            LastName = "Demirtas",
                            ModifiedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(86)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(89),
                            FirstName = "Cem",
                            IsDeleted = false,
                            LastName = "Ozturk",
                            ModifiedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(89)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(94),
                            FirstName = "Ayse",
                            IsDeleted = false,
                            LastName = "Karaca",
                            ModifiedTime = new DateTime(2024, 12, 28, 9, 16, 41, 511, DateTimeKind.Utc).AddTicks(95)
                        });
                });

            modelBuilder.Entity("SurvivorWebAPI.Data.Entity.Competitor", b =>
                {
                    b.HasOne("SurvivorWebAPI.Data.Entity.Category", "Category")
                        .WithMany("Competitors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SurvivorWebAPI.Data.Entity.Category", b =>
                {
                    b.Navigation("Competitors");
                });
#pragma warning restore 612, 618
        }
    }
}
